# Generated by Django 3.2.18 on 2023-04-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0002_auto_20230423_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='groupsize',
            new_name='group_size',
        ),
    ]
