# Generated by Django 3.2.18 on 2023-04-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0003_rename_groupsize_reservation_group_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='email_address',
        ),
    ]
