# Generated by Django 3.2.18 on 2023-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0004_auto_20230425_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
