# Generated by Django 3.2.18 on 2023-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0005_delete_signup'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time'), name='name of constraint'),
        ),
    ]
