# Generated by Django 3.2.18 on 2023-04-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0006_reservation_name of constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='email_address',
            new_name='email',
        ),
    ]
