# Generated by Django 3.2.18 on 2023-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0007_rename_email_address_reservation_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time'), name='reservation_user_uniq'),
        ),
    ]
