# Generated by Django 3.2.18 on 2023-04-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbooking', '0009_rename_email_reservation_email_address'),
    ]

    
